/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hanghoa;

import Business.BUS_TaiKhoan;
import Data.TaiKhoan;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HaiTruong
 */
public class Gui_TaiKhoan extends javax.swing.JFrame {

    /**
     * Creates new form Gui_TaiKhoan
     */
    private Component frame;
    public Gui_TaiKhoan() {
        initComponents();
        LoadData();
    }
    
    void LoadData() {

        ArrayList<TaiKhoan> list = BUS_TaiKhoan.getInfoTaiKhoan();
        DefaultTableModel model = (DefaultTableModel) Tb_TaiKhoan.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        for (TaiKhoan p : list) {
            String MaTK = p.getMaTK();
            String TenTK = p.getTenTK();
            model.addRow(new Object[]{MaTK, TenTK});
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tb_TaiKhoan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_Them = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        t_MaTK = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        t_TenTK = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tb_TaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Tài Khoản", "Tên Tài Khoản"
            }
        ));
        jScrollPane1.setViewportView(Tb_TaiKhoan);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("TÀI KHOẢN");

        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã Tài Khoản");

        t_MaTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_MaTKActionPerformed(evt);
            }
        });

        jLabel3.setText("Tên Tài Khoản");

        t_TenTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_TenTKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(265, 265, 265)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(t_MaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(t_TenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(t_MaTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(t_TenTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Them, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm thông tin này?", "Confirm", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try {

                TaiKhoan TaiKhoan = new TaiKhoan();
                TaiKhoan.setMaTK(t_MaTK.getText());
                TaiKhoan.setTenTK(t_TenTK.getText());
                
                int kq = BUS_TaiKhoan.ThemTaiKhoan(TaiKhoan.getMaTK(),TaiKhoan.getTenTK());
                if (kq == 1) {
                    JOptionPane.showConfirmDialog(null, "Thêm thành công!", "Thông báo", -1, 1);
                } else {
                    JOptionPane.showConfirmDialog(null, "Thêm mới không thành công! Vui lòng thực hiện lại!", "Thông báo", -1, 2);
                }
            } catch (Exception ex) {
                // ex.printStackTrace();
                JOptionPane.showConfirmDialog(null, "Thêm mới không thành công! Vui lòng thực hiện lại!", "Thông báo", -1, 2);
            }
            LoadData();
        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void t_MaTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_MaTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_MaTKActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa thông tin này?", "Confirm", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

        DefaultTableModel model = (DefaultTableModel) Tb_TaiKhoan.getModel();
        if(Tb_TaiKhoan.getSelectedRow() == -1){
            if(Tb_TaiKhoan.getRowCount() == 0){
                JOptionPane.showMessageDialog(frame, "Bảng không có số liệu.", "Inane error", JOptionPane.WARNING_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(frame, "Bạn phải chọn một tài khoản", "Inane error", JOptionPane.WARNING_MESSAGE);
            }
        }else{
                    TaiKhoan TaiKhoan = new TaiKhoan();
                    TaiKhoan.setMaTK(t_MaTK.getText());
                    TaiKhoan.setTenTK(t_TenTK.getText());
                    int kq = BUS_TaiKhoan.SuaTaiKhoan(TaiKhoan.getMaTK(), TaiKhoan.getTenTK());
                    if (kq == 1) {
                    JOptionPane.showConfirmDialog(null, "Cập nhật thành công!", "Thông báo", -1, 1);
                } else {
                    JOptionPane.showConfirmDialog(null, "Cập nhập không thành công! Vui lòng thực hiện lại!", "Thông báo", -1, 2);
                }
        }
        }
        LoadData();
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa thông tin này?", "Confirm", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

        DefaultTableModel model = (DefaultTableModel) Tb_TaiKhoan.getModel();
        if(Tb_TaiKhoan.getSelectedRow() == -1){
            if(Tb_TaiKhoan.getRowCount() == 0){
                JOptionPane.showMessageDialog(frame, "Bảng không có số liệu.", "Inane error", JOptionPane.WARNING_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(frame, "Bạn phải chọn một tài khoản", "Inane error", JOptionPane.WARNING_MESSAGE);
            }
        }else{

                    int kq = BUS_TaiKhoan.XoaTaiKhoan(t_MaTK.getText());
                    if (kq == 1) {
                    JOptionPane.showConfirmDialog(null, "Cập nhật thành công!", "Thông báo", -1, 1);
                } else {
                    JOptionPane.showConfirmDialog(null, "Cập nhập không thành công! Vui lòng thực hiện lại!", "Thông báo", -1, 2);
                }
        }
        }
        LoadData();
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void t_TenTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_TenTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_TenTKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_TaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_TaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_TaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_TaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_TaiKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tb_TaiKhoan;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t_MaTK;
    private javax.swing.JTextField t_TenTK;
    // End of variables declaration//GEN-END:variables
}
